### ISSUE TITLE
[BUG] wrong messages

### ISSUE THREAD

**Issue by ghost** [NikitaCartes/EasyAuth#13] opened 2021-09-07 11:55 UTC
**Versions**
* EasyAuth 1.9.6
* Fabric API 0.40.0

**Describe the bug**
not showing messages

**To Reproduce**
1. install it
2. join server

**Expected behavior**
A clear and concise message of login and register.

![imagen](https://user-images.githubusercontent.com/24663715/132340309-54ef03dd-5721-46a1-b7e6-3c21a849e1a0.png)

**Comment by ghost** [comment] 2021-09-07 12:05
1.9.0:
![imagen](https://user-images.githubusercontent.com/24663715/132341621-d57eb25b-585e-4ba7-8226-359a38e0cc7e.png)

**Comment by NikitaCartes** [comment] 2021-09-09 09:49
I can't reproduce it, but sometimes first messages appear at wrong language.
Which language do you use at your client?
This error appears after every restart?
Which version of Fabric (not api) do you use?

**Comment by ghost** [comment] 2021-09-27 16:58
my client uses spanish, and i dont remember more, not using a modpack server now :/

**Comment by NikitaCartes** [comment] 2021-09-27 17:24
In that case i will close this issue. Feel free to reopen it.

If someone will face same problem I will add a possibility to disable server-side translation

**Comment by AZMindroma** [comment] 2021-10-05 16:17
Hello! This issue is also happening at me. Ever since 1.9.3 when server-side translations were added, the messages show up like at the screenshot above. My PC has German set as primary language, however there is a German language file so it was expected to work. 
A possibility to disable server-side translations would be greatly appreciated, as using old versions on the long run won't give the server the possibility to benefit from new features (like the Alias).

Versions
- EasyAuth: 1.9.3+
- Fabric: 0.7.4
- Fabric API: 0.40.1

Thanks a lot in advance! :)

**Comment by NikitaCartes** [comment] 2021-10-07 21:46
@AZMindroma I will add that option.

Can you give me `latest.log` from start and up to `Preparing spawn area`? That section doesn't contain any private data (like ip), but it can help me to find source of that problem.

**Comment by AZMindroma** [comment] 2021-10-09 22:23
Thanks a million! Here's the file: [latest.log](https://github.com/NikitaCartes/EasyAuth/files/7316490/latest.log)

**Closed as completed** 2022-01-10 21:15 UTC
Labels: bug, Waiting for response
